#!/bin/sh

LUA=lua

echo "Starting server"
$LUA server.lua &
pid=$!
trap "kill $pid > /dev/null 2> /dev/null" 0

for((i=0;i<10;++i));do if test -r lnxt.ludo;then break;else sleep 1;fi;done

echo "Starting client"
$LUA joystick_client.lua

echo "Demo finished. Removing object reference files."
rm -f *.ludo
